### ISSUE TITLE
How about a Spanish translation?

### ISSUE THREAD

**Issue by lmponcio** [Victorhpinheiro/git-cheat-sheet#1]
Hi Victor 

I was thinking I could add a new markdown file (same content) with the comments in Spanish

I would leave a link in the original README.md, so the translation can be accessed with one click

Let me know if you think it is a good idea - It would be a good exercise for me to review all the commands

I will wait for your thumbs up to move forward - If you prefer not to add it it's all good too :)   

Regards!

**Comment by Victorhpinheiro** [comment]
Sounds great!
